// 具名选项类型契约：插件工厂与按钮工厂的导出签名依赖这些类型，
// 主题（如 geek 的 sidebar-toggle）在类型检查下直接引用
export type * from './types'

export * from './plugins/background'
export * from './plugins/barrage'
export * from './plugins/catalog'
export * from './plugins/charts'
export * from './plugins/clickEffects'
export * from './plugins/codeCopy'
export * from './plugins/codeHighlight'
export * from './plugins/codeLang'
export * from './plugins/codeLinenumbers'
export * from './plugins/codeTrafficLight'
export * from './plugins/colorMode'
export * from './plugins/commentsAvatars'
export * from './plugins/darkMode'
export * from './plugins/donation'
export * from './plugins/emoji'
export * from './plugins/footer'
export * from './plugins/imagePreview'
export * from './plugins/license'
export * from './plugins/live2d'
export * from './plugins/lock'
export * from './plugins/musicPlayer'
export * from './plugins/notation'
export * from './plugins/notice'
export * from './plugins/postBottomImage'
export * from './plugins/postMessage'
export * from './plugins/postTopImage'
export * from './plugins/qrcode'
export * from './plugins/signature'
export * from './plugins/tools'
export * from './plugins/tools/buttons'
export * from './plugins/webTag'
